services:
  dice:
    build: ./
    env_file: .env
    ports:
      - ${STREAMLIT_SERVER_PORT}:${STREAMLIT_SERVER_PORT}
    volumes:
      - ./:/app
    networks:
      - proxy
    environment:  
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT}
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dice-ssl.entrypoints=https"
      - "traefik.http.routers.dice-ssl.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.dice-ssl.tls=true"
      - "traefik.http.routers.dice-ssl.tls.certresolver=http"
      - "traefik.http.routers.dice-ssl.middlewares=default@file"
      - "traefik.http.routers.expedicenses-ssl.service=dice-ssl"
      - "traefik.http.services.dice-ssl.loadbalancer.server.port=${STREAMLIT_SERVER_PORT}"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    name: proxy
    driver: bridge
    attachable: true